# Server configuration
server:
  port: 8082

# Spring Boot specific configurations
spring:
  application:
    name: activityservice
  # MongoDB database configuration
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessactivity
      database: fitnessactivity
  # Spring Security configuration for JWT validation
  security:
    oauth2:
      resourceserver:
        jwt:
          # This URI is for Google's public keys to verify Firebase JWTs
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/fitness-app-b9035

# Custom application properties
api:
  cors:
    # Allows your React frontend (running on port 3000) to call this backend
    allowed-origins: "http://localhost:3000"

